version: '3.8'

networks:
  default:
    name: 'frm'
  
volumes:
  frm-pg:
  frm-logs:
    
services:
  postgres:
    container_name: 'frm-pg'
    image: 'postgres:17.4'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'forum'
    volumes:
      - frm-pg:/var/lib/postgresql/data
      
    
  opensearch:
    container_name: 'frm_os'
    
    image: 'opensearchproject/opensearch:2'
    
    ports:
      - '9200:9200'
      - '9600:9600'
    
    environment:
      discovery.type: 'single-node'
      plugins.security.disabled: 'true'
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: 'SuperSecurePass123!'
    
    volumes:
      - frm-logs:/usr/share/opensearch/data
      
  opensearch-dashbords:
    container_name: 'frm_osd'
    image: 'opensearchproject/opensearch-dashboards:latest'
    ports:
      - '5601:5601'
    environment:
      OPENSEARCH_HOSTS: '["http://frm_os:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: 'true'
    depends_on:
      - opensearch